variable "talos_version" {
  description = "The version used to create the talos image"
  type        = string
}

variable "talos_extensions" {
  description = "The extensions to use in creating the factory.talos.dev installer image"
  type        = list(string)
  default     = []
}

variable "image_arch" {
  description = "The architecture if the install image"
  type        = string
  default     = "amd64"
}

variable "image_platform" {
  description = "The platform for the image created for"
  type        = string
  default     = "metal"
}

variable "is_image_secureboot" {
  description = "Wether to use the installer with secureboot or not"
  type        = bool
  default     = false
}

variable "machine_secrets" {
  description = "The secret used to connect Talos nodes together"
  sensitive   = true
}

variable "client_configuration" {
  description = "The secret used to authenticate to a Talos node"
  sensitive   = true
}

variable "node_is_controlplane" {
  description = "Wether to configure this node as a controlplane or a worker node"
  type        = bool
  default     = false
}

variable "kubernetes_version" {
  description = "The version of kubernetes for talos to use"
  type        = string
  default     = "v1.33.0"
}

variable "talos_extra_kernel_args" {
  description = "Extra kernels arguments to give to the node"
  type        = list(string)
  default     = []
}

variable "talos_kernel_modules" {
  description = "Kernel Modules to load into the node"
  type        = list(string)
  default     = []
}

variable "talos_machine_sysctls" {
  description = "Sysctls to set into the node"
  type        = map(string)
  default     = {}
}

variable "cluster_name" {
  description = "The name of the cluster that the node will join"
  type        = string
}

variable "cluster_endpoint" {
  description = "The cluster endpoint for the node to join"
  type        = string
  default     = null
  nullable    = true
}
variable "cluster_inline_manifests" {
  description = "The paths to manifest files to load onto Talos after cluster creation"
  type = map(string)
  default = {}
}
variable "cluster_extra_manifests" {
  description = "An array of raw text urls containing extra manifests to download and load after cluster creation"
  type = list(string)
  default = []
}
variable "node_address" {
  description = "The network reachable address of the Talos node to configure"
  type        = string
}

variable "config_templates" {
  description = "The map locations of the template and the parameters for it"
  # type        = map(map({}))
  default     = {}
}

variable "node_labels" {
  description = "The labels added to the node"
  type        = map(string)
  default     = {}
}
variable "node_annotations" {
  description = "The annotations added to the node"
  type        = map(string)
  default     = {}
}
variable "node_taints" {
  description = "The taints added to the node"
  type        = map(string)
  default     = {}
}
variable "use_wireguard" {
  description = "Whether to use wireguard as the underlying network or not"
  type        = bool
  default     = false
}
variable "use_wireguard_preshared_key" {
  description = "Whether to use a presharedKey for wireguard (Highly Recommended)"
  type        = bool
  default     = true
}
variable "wg_iface_name" {
  description = "Name of the Wireguard link (interface)"
  type        = string
  default     = "wgc"
}

variable "wg_listen_port" {
  description = "Specifies a device's listening port (UDP). If not specified, a random port will be chosen."
  type        = number
  nullable    = true
  default     = null
}

variable "wg_firewall_mark" {
  description = "Specifies a device's firewall mark. Useful for advanced routing setups, marking packets originating from this device."
  type        = number
  default     = null
  nullable    = true
}

variable "wg_peers" {
  description = <<EOF
    publicKey | string  |	Specifies the public key of this peer.
      Can be extracted from private key by running wg pubkey < private.key.	
    presharedKey  | string  |	Specifies the preshared key for this peer (base64 encoded).
      Can be generated by wg genpsk.
      Optional, this key provides an additional layer of symmetric-key cryptography
      to the peer connection.	
    endpoint  | AddrPort(string)  |	Specifies the endpoint of this peer entry.
      Format: <IP address>:<port>.
      If not set, the peer should connect to us without us connecting to it first.	
    persistentKeepaliveInterval | Duration(string)  |	Specifies the persistent keepalive interval for this peer.
      Field format accepts any Go time.Duration format (‘1h’ for one hour, ‘10m’ for ten minutes).	
    allowedIPs  | []Prefix(list of strings)	AllowedIPs specifies a list of allowed IP addresses in CIDR notation for this peer.
      These IPs will be routed to this peer, and defines which IPs this peer is allowed to use.
  EOF
  type = list(object({
    publicKey                   = string
    presharedKey                = optional(string)
    endpoint                    = optional(string)
    persistentKeepaliveInterval = optional(string)
    allowedIPs                  = list(string)
  }))
  default = []
}

variable "wg_up" {
  description = "Bring the link up or down. If not specified, the link will be brought up."
  type        = bool
  default     = true
}

variable "wg_mtu" {
  description = "Configure LinkMTU (Maximum Transmission Unit) for the link. If not specified, the system default LinkMTU will be used (usually 1500)."
  type        = number
  default     = null
  nullable    = true
}

variable "wg_addresses" {
  description = <<EOF
  address | Prefix(string)  | IP address to be assigned to the link.
    This field must include the network prefix length (e.g. /24 for IPv4, /64 for IPv6).	

  routePriority | number  | Configure the route priority (metric) for routes created for this address.
    If not specified, the system default route priority will be used.
  EOF
  type = list(object({
    address       = string
    routePriority = optional(number)
  }))
  default     = null
  nullable    = true
  validation {
    condition     = var.use_wireguard == false || var.wg_addresses != null
    error_message = "wg_addresses must be set if use_wireguard is true."
  }
}
variable "wg_keep_alive" {
  description = "How long is the wg connection kept alive"
  type        = string
  default     = "5s"
}
variable "wg_allowed_ips" {
  description = "Allowed ip addresses this node can access(careful that it doesn't overlap with other networks, disabling network access)"
  type        = list(string)
  default     = []
}
variable "wg_routes" {
  description = <<EOF
    destination | Prefix(string)  |  The route's destination as an address prefix.
      If not specified, a default route will be created for the address family of the gateway.
    gateway | Addr(string)  |    The route's gateway (if empty, creates link scope route).
    source  | Addr(string)  |    The route's source address (optional).
    metric  | uint32(number)  |  The optional metric for the route.
    mtu | uint32(number)  |  The optional MTU for the route.
    table | RoutingTableName(string)  |  The routing table to use for the route.
      If not specified, the main routing table will be used.
  EOF
  type = list(object({
    destination = optional(string)
    gateway     = optional(string)
    source      = optional(string)
    metric      = optional(number)
    mtu         = optional(number)
    table       = optional(string)
  }))
  default = []
}

variable "wg_multicast" {
  description = "Set the multicast capability of the link."
  type        = bool
  default     = null
  nullable    = true
}
variable "wg_override_endpoint" {
  description = "In case of tunneling, you should specify the endpoint of the tunnel"
  type        = string
  default = null
  nullable = true
}
variable "apply_talos_config" {
  description = "wether to apply the auto generated config or not, this is mainly for debugging"
  type        = bool
  default     = true
}