variable "filename" {
  description = "The path and filename to write the wireguard config file to"
  type = string
  default = "./wireguard.conf"
}
variable "wg_iface_name" {
  description = "The name of the wireguard interface on the Talos machine config"
  type        = string
  default     = "wgc"
}
variable "wg_listen_port" {
  description = "This node's listening port for wireguard"
  type        = number
  nullable    = true
  default     = null
}

variable "wg_peers" {
  description = <<EOF
    publicKey | string  |	Specifies the public key of this peer.
      Can be extracted from private key by running wg pubkey < private.key.	
    presharedKey  | string  |	Specifies the preshared key for this peer (base64 encoded).
      Can be generated by wg genpsk.
      Optional, this key provides an additional layer of symmetric-key cryptography
      to the peer connection.	
    endpoint  | AddrPort(string)  |	Specifies the endpoint of this peer entry.
      Format: <IP address>:<port>.
      If not set, the peer should connect to us without us connecting to it first.	
    persistentKeepaliveInterval | Duration(string)  |	Specifies the persistent keepalive interval for this peer.
      Field format accepts any Go time.Duration format (‘1h’ for one hour, ‘10m’ for ten minutes).	
    allowedIPs  | []Prefix(list of strings)	AllowedIPs specifies a list of allowed IP addresses in CIDR notation for this peer.
      These IPs will be routed to this peer, and defines which IPs this peer is allowed to use.
  EOF
  type = list(object({
    publicKey                   = string
    presharedKey                = optional(string)
    endpoint                    = optional(string)
    persistentKeepaliveInterval = optional(string)
    allowedIPs                  = list(string)
  }))
  default = []
}

variable "wg_addresses" {
  description = "The addresses this node is reachable within the wg network"
  type        = list(string)
  default     = null
  nullable    = true
}
variable "wg_preshared_key" {
  description = "The presharedKey for wireguard communication (Highly Recommended)"
  type        = string
  default     = null
}
variable "wg_keep_alive" {
  description = "How long is the wg connection kept alive"
  type        = string
  default     = "5s"
}
variable "wg_allowed_ips" {
  description = "Allowed ip addresses this node can access(careful that it doesn't overlap with other networks, disabling network access)"
  type        = list(string)
  default     = []
}
variable "wg_mtu" {
  description = "The mtu used by the device"
  type = number
  default = 1500
}